-- INSERT INTO favorite_maps
--   (map_id,user_id)
-- VALUES
--   (3, 2);
-- INSERT INTO favorite_maps
--   (map_id,user_id)
-- VALUES
--   (1, 4);
-- INSERT INTO favorite_maps
--   (map_id,user_id)
-- VALUES
--   (2, 5);
-- INSERT INTO favorite_maps
--   (map_id,user_id)
-- VALUES
--   (1, 5);
-- INSERT INTO favorite_maps
--   (map_id,user_id)
-- VALUES
--   (3, 5);
-- INSERT INTO favorite_maps
--   (map_id,user_id)
-- VALUES
--   (2, 1);
-- INSERT INTO favorite_maps
--   (map_id,user_id)
-- VALUES
--   (3, 1);
