-- INSERT INTO contributors
--   (map_id,user_id)
-- VALUES
--   (1, 2);
-- INSERT INTO contributors
--   (map_id,user_id)
-- VALUES
--   (2, 4);
-- INSERT INTO contributors
--   (map_id,user_id)
-- VALUES
--   (3, 2);
-- INSERT INTO contributors
--   (map_id,user_id)
-- VALUES
--   (3, 5);
