DROP TABLE IF EXISTS flags
CASCADE;
CREATE TABLE flags
(
  id SERIAL PRIMARY KEY NOT NULL,
  latlong POINT NOT NULL,
  address VARCHAR(255) NOT NULL,
  map_id INTEGER REFERENCES maps(id) ON DELETE CASCADE,
  title VARCHAR(255) NOT NULL,
  description VARCHAR(255) NOT NULL,
  image VARCHAR(255) NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE
);
