DROP TABLE IF EXISTS favorite_maps
CASCADE;
CREATE TABLE favorite_maps
(
  id SERIAL PRIMARY KEY NOT NULL,
  map_id INTEGER REFERENCES maps(id) ON DELETE CASCADE,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
);
